Build in chroot (mmdebstrap)
intel/ScaffoldingForGramine pull request #18
Opened 2023-10-19 06:11 UTC by woju

(see commit message)

2023-10-19 06:11 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-19 06:27 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/1513ee21f0874a76962eb8aa73ae1332

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ab33599004bc46db80a6fdd7cd48125f) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/1fdfe919ff44473e8fbb95c44c32e020) **FAILURE** in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b891e79b9ec147e1a564ba67e62bf304) SUCCESS in 39s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/ebee10f1877444129b4a0bced725e9cb) **FAILURE** in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/f2c14ac03e134256b20be5f19244df34) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0bf10838c03a4731983c9932ab948f73) **FAILURE** in 2m 28s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/417c6a74f5dd47a5892c884d8d8d7cce) **FAILURE** in 3m 06s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/fe29b4613be74273be62f295ec339b22) **FAILURE** in 2m 26s

2023-10-19 08:13 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 32 files reviewed, 3 unresolved discussions (waiting on @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
I'm not sure if we want to reitre `--sgx-key` as user can have a multiple keys, per project for example. I can imagine that the dev key is also in repo.

How can I run gramine-direct now?

All this wasn't documented.
___
*[`graminescaffolding/builder.py` line 222 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5ydJQ7r8j5GIhmOtU:-Nh5ydJQ7r8j5GIhmOtV:b9ab3mv) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/builder.py#L222)):*
> ```Python
>         'python3-flask',
>         'python3.11',
>         'uwsgi',
> ```

I would prefer depends to be installed in docker.
We have discussed this previously, my idea was to:
- init debian image using mmdebstrap,
- put it into docker,
- continue in docker.

I'm also not sure if we shouldn't have this definitions in dedicated files, as if user will want to add his own builders he won't need to edit our code.
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-Nh5zNUXCefT2F5AKEOx:b-u9rem6) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
> ```
>     { path = "/usr/bin/gramine-ratls", uri = "file:/usr/bin/gramine-ratls" },
> 
>     { path = "/etc/nginx/nginx.conf", uri = "file:/app/.scag/nginx.conf" },
> ```

This file was moved to confs, before I think we should use a "hidden" files in docker. I guess `.scag` directory should be added to `.dockerignore`.


<!-- Sent from Reviewable.io -->

2023-10-19 08:16 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 32 files reviewed, 4 unresolved discussions (waiting on @woju)

___
*[`graminescaffolding/templates/mmdebstrap-hooks/customize.sh` line 10 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh6-LXW048RfifKcdFL:-Nh6-LXW048RfifKcdFM:b420c8b) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/mmdebstrap-hooks/customize.sh#L10)):*
> ```Shell
> 
> {% block manifest -%}
> chroot "$1" gramine-manifest \
> ```

This also highlights this issue, as user might not be aware to use chroot to run custom commands inside our new build system.



_Code quote:_
```Shell
chroot "$1"
```


<!-- Sent from Reviewable.io -->

2023-10-20 09:14 UTC, piotrpalcz submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 32 files reviewed, 8 unresolved discussions (waiting on @oshogbo and @woju)

___
*[`graminescaffolding/__main__.py` line 171 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBFrchD6Blo9GHu-ns:-NhBFrchD6Blo9GHu-nt:b9uhlli) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L171)):*
> ```Python
>     builder = parser(args=args, standalone_mode=False)
> 
>     if bootstrap:
> ```

`if bootstrap:` conditional duplicated, possibly could be merged 
___
*[`graminescaffolding/__main__.py` line 179 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGXu6-6_zfkNR8P3z:-NhBGXu6-6_zfkNR8P4-:b3bqdk3) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L179)):*
> ```Python
> @main.command('build')
> @click.option('--conf', default=_builder.SCAG_CONFIG_FILE,
>     type=str, # XXX not click.File, this is relative to --project-dir
> ```

` # XXX not click.File` what does it mean, why is it in this comment section?
___
*[`graminescaffolding/__main__.py` line 210 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGsd82rAHiAEPeO2u:-NhBGsd82rAHiAEPeO2v:b-a33tyb) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L210)):*
> ```Python
>     Real steps for build Gramine application using Scaffolding framework.
>     """
>     project_dir = pathlib.Path(project_dir)
> ```

Switching to `ctx` will guarantee that`project_dir` exists? Here the check for `project_dir` existance is dropped
___
*[`graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template` line 7 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBL02CDVUNHrtqNLqA:-NhBL02CDVUNHrtqNLqB:b-a3tegs) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template#L7)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib:/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu"
> {% endraw %}
> ```

If this loader.argv is the only line thats not between raw/endraw - cant it be moved to the top to not open,close and then again open the raw braces?


<!-- Sent from Reviewable.io -->

2023-10-23 10:27 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 10:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 35 files reviewed, 8 unresolved discussions (waiting on @oshogbo and @piotrpalcz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
> How can I run gramine-direct now?

You pick this `docker run` incantation and add at the end `gramine-direct app`. That it also has `aapp.manifest.sgx` doesn't prevent running direct.

> All this wasn't documented.

Yes, this is undocumented, as almost everything in this project. I have pieced together `hacking.rst` with some documentation about developing new frameworks, but those usability things need to be documented.
___
*[`graminescaffolding/__main__.py` line 171 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBFrchD6Blo9GHu-ns:-NhQram87wFud1cyJQrn:b-cmivv5) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L171)):*
<details><summary><i>Previously, piotrpalcz (ppalczew) wrote…</i></summary><blockquote>

`if bootstrap:` conditional duplicated, possibly could be merged
</blockquote></details>

Unfortunately no, there's builder instantiation in the middle.
___
*[`graminescaffolding/__main__.py` line 179 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGXu6-6_zfkNR8P3z:-NhQZW3BEvJ7XBZYj0g8:b-f8mnsx) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L179)):*
<details><summary><i>Previously, piotrpalcz (ppalczew) wrote…</i></summary><blockquote>

` # XXX not click.File` what does it mean, why is it in this comment section?
</blockquote></details>

click has two different facilities for specifying files on command line, `click.File` and `click.Path`. `click.File` will eventually do `open()` on the path that you provide as the value to the option, so this is not what we want (we want the file relative to `--project-dir`, not relative to cwd, as described in `help=`). Therefore `click.File` is unsuitable. The comment is a reminder for all above.
___
*[`graminescaffolding/__main__.py` line 210 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGsd82rAHiAEPeO2u:-NhQ_HLA2imaRyJoU9ZH:b-ghcp4i) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L210)):*
<details><summary><i>Previously, piotrpalcz (ppalczew) wrote…</i></summary><blockquote>

Switching to `ctx` will guarantee that`project_dir` exists? Here the check for `project_dir` existance is dropped
</blockquote></details>

In both `main.command()`s `project_dir` is `click.Path(file_okay=False, dir_okay=True)`, so that checks for the dir's existence. The check here was redundant.
___
*[`graminescaffolding/builder.py` line 222 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5ydJQ7r8j5GIhmOtU:-NhQ__cQCIjwouhZDRVc:b-let0qt) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/builder.py#L222)):*
There's TODO for branching to docker (in `def build()`), for now while we don't have that, it's OK to have it as `mmdebstrap --include`. For now, as long as we *emit* the docker image, it's usable enough for people to deploy.

Remember that you can't have whole process in docker, because signing needs to be done outside.

> I'm also not sure if we shouldn't have this definitions in dedicated files, as if user will want to add his own builders he won't need to edit our code.

If someone wants to have another framework outside of this, s/he can create another package, import this module, inherit from the `Builder` class and add entrypoint to his/her package that will point to that new class. Doesn't need to edit our files, though probably jinja's env needs to be adjusted to point to another template directory (with new templates).

Because those classes are so simple, there's no need to keep them in separate files. The complexity in this project is in templates, not in Python.
___
*[`graminescaffolding/templates/mmdebstrap-hooks/customize.sh` line 10 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh6-LXW048RfifKcdFL:-NhQpd4W9FdAeIMJ4C0c:bywnylk) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/mmdebstrap-hooks/customize.sh#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This also highlights this issue, as user might not be aware to use chroot to run custom commands inside our new build system.
</blockquote></details>

Yep. I've described this in `hacking.rst`. But, the chroot needs to be there (or not), because we're signing outside of the chroot.
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhQcR_u4B4ZMjtB4rHt:byhrcl6) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This file was moved to confs, before I think we should use a "hidden" files in docker. I guess `.scag` directory should be added to `.dockerignore`.
</blockquote></details>

`Dockerfile` needs to be in the context, right? So we can't wholesale ignore it.
___
*[`graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template` line 7 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBL02CDVUNHrtqNLqA:-NhQctcA3zcQ5oVWVzR2:buji9sv) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template#L7)):*
<details><summary><i>Previously, piotrpalcz (ppalczew) wrote…</i></summary><blockquote>

If this loader.argv is the only line thats not between raw/endraw - cant it be moved to the top to not open,close and then again open the raw braces?
</blockquote></details>

No, because it needs to be after `{% set nodejs = %}`, which is inside `{% raw %}`. I can move it near the beginning, so the long block is not broken in the middle, instead I break it right at the top.


<!-- Sent from Reviewable.io -->

2023-10-23 10:28 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 35 files reviewed, 8 unresolved discussions (waiting on @oshogbo and @piotrpalcz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
> How can I run gramine-direct now?

You pick this `docker run` incantation and add at the end `gramine-direct app`. That it also has `aapp.manifest.sgx` doesn't prevent running direct.

> All this wasn't documented.

Yes, this is undocumented, as almost everything in this project. I have pieced together `hacking.rst` with some documentation about developing new frameworks, but those usability things need to be documented.


<!-- Sent from Reviewable.io -->

2023-10-23 10:38 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 35 files reviewed, 7 unresolved discussions (waiting on @piotrpalcz and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
> You pick this `docker run` incantation and add at the end `gramine-direct app`. That it also has `aapp.manifest.sgx` doesn't prevent running direct.

So why don't we want to have a setup option to check if we want to use this or this? Instead we are asking user to change that manually?

>Yes, this is undocumented, as almost everything in this project. I have pieced together `hacking.rst` with some documentation about developing new frameworks, but those usability things need to be documented.

Option you are removing are documented:
https://github.com/intel/ScaffoldingForGramine/blob/stable/Documentation/manpages/scag-build.rst
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhR5qGk7srIjmbebJgI:b-eao1wx) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`Dockerfile` needs to be in the context, right? So we can't wholesale ignore it.
</blockquote></details>

Not sure what you mean.
In code we have done:
`docker build -f .scag/Dockerfile .` and dockerfile was in the context. We still can do the same thing here, and we don't need to use .scag in the app.manifest.template instead we can use a normal dirs like we used to.


<!-- Sent from Reviewable.io -->

2023-10-23 10:39 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 35 files reviewed, 7 unresolved discussions (waiting on @piotrpalcz and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> You pick this `docker run` incantation and add at the end `gramine-direct app`. That it also has `aapp.manifest.sgx` doesn't prevent running direct.

So why don't we want to have a setup option to check if we want to use this or this? Instead we are asking user to change that manually?

>Yes, this is undocumented, as almost everything in this project. I have pieced together `hacking.rst` with some documentation about developing new frameworks, but those usability things need to be documented.

Option you are removing are documented:
https://github.com/intel/ScaffoldingForGramine/blob/stable/Documentation/manpages/scag-build.rst
</blockquote></details>

And:
https://github.com/intel/ScaffoldingForGramine/blob/stable/Documentation/manpages/scag-setup.rst


<!-- Sent from Reviewable.io -->

2023-10-23 10:39 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b159b1728db645bcabf6bf0725e05fb8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/925dd66d982446a99743bd9a6b70dbc9) SUCCESS in 37s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/547c34f33a7c4419b484eb81e7c6b399) **FAILURE** in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/7422685794d2403ca7e9995f4e800e7c) SUCCESS in 40s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/c1022a870357434a84c4d2a5b855ae2c) **FAILURE** in 1m 00s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/1ded0dbb3edd4aa7825d6ab905ebf132) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0f294eb67fc34541a017e3e89d0748e4) **FAILURE** in 59s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/93baf32f3d554200bbd0553750147003) **FAILURE** in 1m 02s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/1ed6dc39b5794cdbae159e2129cabbfe) **FAILURE** in 57s

2023-10-23 19:19 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 19:31 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/3c1f9d54236e46da90811a15115fb092

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/d4dca9c8d767483f9ba960cefc0a4393) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/9db6785b268f46a7b68e07df118ce3f0) **FAILURE** in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/8a05ba9d5f89486290b23cc56f37bfc9) SUCCESS in 39s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0f342faa528a4f9d87b5c53fc750048a) **FAILURE** in 1m 00s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b08c7046d1d1401696b5e1e9190d921f) SUCCESS in 36s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/d272df0a26ea4169877e9d177c627dee) **FAILURE** in 57s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/bafde1fae5c248f09c8d676b30adb2e8) **FAILURE** in 1m 00s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/8cfa69570a964677b1ddbfc665a2e5ab) **FAILURE** in 1m 06s

2023-10-23 20:43 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 20:54 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/0c6d16818bc1473481f475f48713e7d7

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/416d981df5f94e2cbf5ad12c95f19038) SUCCESS in 37s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/8fb6c1c0d17a4a1f82bed1bead6af4a6) **FAILURE** in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/cc7d880caf4c4666a3de7bc75a1fe3b3) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/c44d722b204942a1b926d0749fe742ae) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8eb7d709e66446e68cc83c24245b96ff) SUCCESS in 36s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/b85c11723e6d42e1928dd35d5e86c35a) **FAILURE** in 57s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/054ad8220c604de7bfdce16cc10e65c4) **FAILURE** in 56s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/3507918d6ea2414081671b9709091d3a) **FAILURE** in 1m 00s

2023-10-23 21:17 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 21:34 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/c224aeadd27a41eba6c37e634b095fa5

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/45431d7ece4c4b60a7391bb99caf9e01) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/1d8a550e81044fc1b6d620b719b552e9) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/2725af83dcf144f38fa8b9ba6e22c9ca) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/3ef6a2f3e82a4ca4b267c0547993ec2d) SUCCESS in 1m 00s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/35086497e60f43da93ca400f81cb1834) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/a277fce4e1a542679b8fef5ee5082640) **FAILURE** in 2m 28s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/bdd8c2efa5d24dd58306ed382be06c49) **FAILURE** in 3m 09s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e53dc9ee0cb94af48dfe40be9cd815e4) **FAILURE** in 2m 30s

2023-10-23 21:35 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 21:50 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/f9f589766f4b47d680e0afb602b687d1

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8fe0e01d5f26442a97ba3e8d037f7278) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f033844b980343038fd8261eb52fb2f8) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d10ef005a1054369ba90f3484ff30fce) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/f036b9e06ec34f9a8251aaed40a66f60) SUCCESS in 1m 00s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/6a14287c5b6d4b439d9931a625cd834d) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/2d07abaa7adb40b1a13648e9a512d6c0) **FAILURE** in 2m 22s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/1380ba82b1904bdf858b2df7c92dcb29) **FAILURE** in 2m 38s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/94fcd0664d51493da1e01783f93b25f5) **FAILURE** in 2m 48s

2023-10-23 21:50 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 22:08 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/e705913756524f2b956c9350abb87da6

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/627e60162111431cafb39399ac7e9513) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/1fe2919cf48d4446b9939f7be9f8c1da) SUCCESS in 54s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/1ba8beda39164e6caf40d38a69f53c18) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/d7029922b5784b52abda49a88b887574) SUCCESS in 1m 00s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e5a83491726046bd832188ff62e8adb8) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/15c3351d980e440b98771075e35d17c4) **FAILURE** in 2m 21s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/8c091f20ea774c91b60c65a7794ea82c) **FAILURE** in 3m 53s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/04210707971840d5aa94002e42893d48) **FAILURE** in 3m 11s

2023-10-23 22:23 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 22:38 UTC, gramine-scaffolding commented
Build canceled.

2023-10-23 22:38 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-23 22:55 UTC, gramine-scaffolding commented
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/f600c303236549ffbff0dca7d0e7226a

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/db39d160461b4f2c9cfe08aa5b6db69b) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a9288940d22a4e55bf199958747d7637) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/57a19980bb34477a946c049e064378ff) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/eae3167a4e5b4c8687181c32d168fb46) SUCCESS in 1m 01s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/19fce10bd4044cb7b47da9ec46b35df8) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/feadf16c59a840fca19caaa09a2c8d22) SUCCESS in 2m 41s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/3249e8fb21804cea93e53fb64fa4ffe4) SUCCESS in 2m 53s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/243bf5cb5a424e4eb9ffb2ebcfe8d2d4) SUCCESS in 2m 58s

2023-10-24 09:58 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 42 files reviewed, 7 unresolved discussions (waiting on @oshogbo and @piotrpalcz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

And:
https://github.com/intel/ScaffoldingForGramine/blob/stable/Documentation/manpages/scag-setup.rst
</blockquote></details>

Done.
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhR7RYZDdQgdjTK2B6b:b-ywkn2s) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Not sure what you mean.
In code we have done:
`docker build -f .scag/Dockerfile .` and dockerfile was in the context. We still can do the same thing here, and we don't need to use .scag in the app.manifest.template instead we can use a normal dirs like we used to.
</blockquote></details>

I mean, if we added `.scag` to `.dockerignore`, then `docker build -f .scag/Dockerfile .` wouldn't work anymore. I want to keep files we create hidden and separate from the root directory, so they won't be in the face of the user who would like to iterate on the app.


<!-- Sent from Reviewable.io -->

2023-10-24 09:59 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 42 files reviewed, 7 unresolved discussions (waiting on @oshogbo and @piotrpalcz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5xvxU4ccEb2Ml7f51):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

And:
https://github.com/intel/ScaffoldingForGramine/blob/stable/Documentation/manpages/scag-setup.rst
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-25 13:38 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 42 files reviewed, 5 unresolved discussions (waiting on @piotrpalcz and @woju)

___
*[`-- commits` line 31 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-78z0154bRBc-9TD):*
You can steal my changes while fixup.
___
*[`Documentation/configuration.rst` line 17 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-Jnq9OXkGAwBguYA:-Nhb-JnrCE4ymEY_mATf:b-577zqq) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5b1f3308cb16d5b433eada7a54efc4c2da3782c6/Documentation/configuration.rst#L17)):*
> ```reStructuredText
> 
> ``application.framework`` (string)
>     Framework. One of ``python_plain``, ``flask``, ``nodejs_plain``.
> ```

I think a bulletpoints would be better here.
___
*[`debian/control` line 18 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-WZz2GrIuDescXzJ:-Nhb-WZz2GrIuDescXzK:bq6yyzq) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5b1f3308cb16d5b433eada7a54efc4c2da3782c6/debian/control#L18)):*
> ```
>  python3-pytest,
>  python3-click,
>  python3-docker,
> ```

I guess this has to be reported to Pawel as a new dep.
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-Nhb0MFEA3T5qkXVv5m5:b-3k9jdi) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I mean, if we added `.scag` to `.dockerignore`, then `docker build -f .scag/Dockerfile .` wouldn't work anymore. I want to keep files we create hidden and separate from the root directory, so they won't be in the face of the user who would like to iterate on the app.
</blockquote></details>

Ok, I just don't like that we are including in manifest files from `.scag`? I think they should be moved into the right place, and ideally, `.scag` shouldn't be copied. Don't we copy the whole image twice now, once as a root fs (`/`) and ones as `.scag` (precisely as `rootfs.tar`)?


<!-- Sent from Reviewable.io -->

2023-10-25 21:39 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-25 21:41 UTC, woju reviewed
> Dismissed @piotrpalcz from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 43 files reviewed, 1 unresolved discussion (waiting on @oshogbo and @piotrpalcz)

___
*[`-- commits` line 31 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-78z0154bRBc-9TD):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You can steal my changes while fixup.
</blockquote></details>

Thanks.
___
*[`Documentation/configuration.rst` line 17 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-Jnq9OXkGAwBguYA:-NhcctLIDa9QXBNixMB6:boh0rin) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5b1f3308cb16d5b433eada7a54efc4c2da3782c6/Documentation/configuration.rst#L17)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think a bulletpoints would be better here.
</blockquote></details>

Done. Not a problem, until the list grows significantly, then we'll wrap it back.
___
*[`debian/control` line 18 at r9](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nhb-WZz2GrIuDescXzJ:-NhcabPuB9DOSpY1pOM0:b-p6y9hy) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5b1f3308cb16d5b433eada7a54efc4c2da3782c6/debian/control#L18)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess this has to be reported to Pawel as a new dep.
</blockquote></details>

I don't think so, this is from Docker people, part of "docker". I'll ask for clarification in the next call.
___
*[`graminescaffolding/__main__.py` line 171 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBFrchD6Blo9GHu-ns:-NhcasCJ-eToykrMUtvx:b3rzpur) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L171)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Unfortunately no, there's builder instantiation in the middle.
</blockquote></details>

Resolving based on conversation on priv.
___
*[`graminescaffolding/__main__.py` line 179 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGXu6-6_zfkNR8P3z:-Nhcb5ntDLJQ62EVrtnw:b3rzpur) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L179)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

click has two different facilities for specifying files on command line, `click.File` and `click.Path`. `click.File` will eventually do `open()` on the path that you provide as the value to the option, so this is not what we want (we want the file relative to `--project-dir`, not relative to cwd, as described in `help=`). Therefore `click.File` is unsuitable. The comment is a reminder for all above.
</blockquote></details>

Resolving based on conversation on priv.
___
*[`graminescaffolding/__main__.py` line 210 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBGsd82rAHiAEPeO2u:-Nhcb8VI66gsrz9M85Qz:b3rzpur) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/__main__.py#L210)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

In both `main.command()`s `project_dir` is `click.Path(file_okay=False, dir_okay=True)`, so that checks for the dir's existence. The check here was redundant.
</blockquote></details>

Resolving based on conversation on priv.
___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhcbDLd-9XfDsAC-p0v:bj8u2ki) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ok, I just don't like that we are including in manifest files from `.scag`? I think they should be moved into the right place, and ideally, `.scag` shouldn't be copied. Don't we copy the whole image twice now, once as a root fs (`/`) and ones as `.scag` (precisely as `rootfs.tar`)?
</blockquote></details>

So maybe we should, instead of just copying whole repo to `/app`, maybe we can:
- copy whole repo to `/app`
- copy say `/app/etc` to say `/usr/local/etc`
- render `app.manifest` from `.scag/app.manifest.template`
- remove `/app/.scag`.

Does that sound OK?
___
*[`graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template` line 7 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-NhBL02CDVUNHrtqNLqA:-NhcbpT3CSNG_6B144dh:b3rzpur) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/nodejs_plain/app.manifest.template#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, because it needs to be after `{% set nodejs = %}`, which is inside `{% raw %}`. I can move it near the beginning, so the long block is not broken in the middle, instead I break it right at the top.
</blockquote></details>

Resolving based on conversation on priv.


<!-- Sent from Reviewable.io -->

2023-10-25 21:55 UTC, gramine-scaffolding commented
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/cfd8dc25e07a4c8e8cf633ff28a83267

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/7a7d3f891aa24085bf3c618685b5965f) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/da8cb215de5e4e00ac3078279d315262) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a48377ed6a5a4295a839e81c7c325258) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/55fb13565da14a9aaac8fba225dca1ab) SUCCESS in 1m 01s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/1c43e2ee227b488d9f57126475392131) SUCCESS in 36s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/f5a0fb65288c4ac1a8be1823e75edeaa) SUCCESS in 2m 53s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/896efe081e2c4145aac6b2919733293d) SUCCESS in 2m 53s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/50eb6d00a3ce4372866d192ec4ebfb32) SUCCESS in 3m 05s

2023-10-26 09:18 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 09:23 UTC, oshogbo requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 43 files reviewed, 1 unresolved discussion (waiting on @piotrpalcz and @woju)

___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhfHZYwAanE90_NQt4x:bmb8v1z) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

So maybe we should, instead of just copying whole repo to `/app`, maybe we can:
- copy whole repo to `/app`
- copy say `/app/etc` to say `/usr/local/etc`
- render `app.manifest` from `.scag/app.manifest.template`
- remove `/app/.scag`.

Does that sound OK?
</blockquote></details>

You mean `/app/.scag/etc` ?
Sounds good.


<!-- Sent from Reviewable.io -->

2023-10-26 09:29 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18)* status: 0 of 43 files reviewed, 1 unresolved discussion (waiting on @oshogbo and @piotrpalcz)

___
*[`graminescaffolding/templates/frameworks/flask/app.manifest.template` line 37 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-Nh5zNUXCefT2F5AKEOw:-NhfJ0ku4jx9y9KyRUgV:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e2ad137ac00d1a9c49b5af30b647973f232531/graminescaffolding/templates/frameworks/flask/app.manifest.template#L37)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You mean `/app/.scag/etc` ?
Sounds good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 09:34 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b7bc35d1727a40f89e21c47fcbafd150

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/070e412ea4634c069630bf94d245a689) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/ce30e4a8ebcb42279eeee39ca21d79a0) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/19e53eb952dd4d6a9935d0fb8c9d2a5a) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/bbc97b2c55834bd399cef6d62cbc9bfa) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e417495cc8b64915871de4bdd1c131cf) SUCCESS in 38s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/191aec353fa345a09863d3fc1451b9db) **FAILURE** in 1m 56s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/cfcd5c6acb644d90a9e67e021c43adf6) SUCCESS in 3m 14s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/54465ad9389c420d910523699bef6190) **FAILURE** in 2m 39s

2023-10-26 09:39 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 09:51 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/8c12631f6f764522a29efec60f730af8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/1ccb5deaab3d4119b2106a3e463bb0b4) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f3916e22683a479698ba9d09cf5ba86a) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/ddfd0953648f47e89e63a9f59bd624d9) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/fe34f0c1a63144c79d4d2a624bf60f31) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/752ecc9b656b4545918464679660146b) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c06a73a92c7944bcb1c004e7eb286da5) **FAILURE** in 57s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/972a9de7bfb5424385d0506848e26230) **FAILURE** in 59s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/7b70272dd7984e84879fd57bc2361e08) **FAILURE** in 1m 00s

2023-10-26 10:12 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 10:16 UTC, gramine-scaffolding commented
Build canceled.

2023-10-26 10:16 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 10:23 UTC, gramine-scaffolding commented
Build canceled.

2023-10-26 10:23 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 10:33 UTC, gramine-scaffolding commented
Build canceled.

2023-10-26 10:33 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 10:49 UTC, gramine-scaffolding commented
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/babcf2b55c0b4ba9b62d72f984dc6a1b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/6b96738b7c37463e928991cfedd0bcf1) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/54b748b9210b4ca38cf6f6c0c612b2bf) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/54f9578edb52455486c9bf3cf4a4facb) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/1d6fe92312af4c248c0ca67ff91ff6c5) SUCCESS in 1m 01s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/7e088c53db7f493fade9e064c924fde5) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6f8a537396e246b2a5cb105d700c0198) SUCCESS in 2m 44s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/5fa79ec5c7824a11a180501e3861ff5e) **FAILURE** in 2m 01s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/cbba536aae174479865f1c2a8b8819ad) SUCCESS in 3m 19s

2023-10-26 10:59 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 11:17 UTC, gramine-scaffolding commented
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/c38421cbdcac4a5bba1cadfdd79fd1ef

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/1094f7d227d64defbdbaa540531be25a) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f406bf17efa74063958ac7bd97fef7c7) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d701edb7bb2f4e1e9b3b4e2ac357b21d) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/bc4911ff53d64efd81f54913f84de66a) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/31e22934a49d42b884be97715fb6a461) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/58b59c87516e4ca1ac7674da5a7cb5bd) SUCCESS in 3m 16s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/07408678feee47f4903582a873358cf7) SUCCESS in 3m 16s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/8e4d405f9247442e83051bbcb8599ab7) SUCCESS in 3m 43s

2023-10-26 11:53 UTC, gramine-scaffolding commented
Starting check jobs.

2023-10-26 12:12 UTC, gramine-scaffolding commented
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/466abcfe54c0467c9bc17d1d19b1844e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b06ec95003d349d7a56fd80d6d8c8cfe) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/089d41f9de144ea299cfb8b3a1e8ce7b) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/0c786188b7914922827bc534b1bee283) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/22b0a1e2d2bd48139e1c292511fb24ec) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/24fb086c7cd549e892aab2c47c7e9de5) SUCCESS in 40s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/08760823a6504d04a4d304e1f6f45447) SUCCESS in 3m 17s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c747155643a3441683e14a01e92103f7) SUCCESS in 3m 23s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/2e4f124b82ea418ca64ecb36cf251cd4) SUCCESS in 3m 47s

2023-10-26 12:17 UTC, oshogbo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/18#-:-NhfucOx3UGqHHkdt7uQ:bnfp4nl)* status: 0 of 43 files reviewed, all discussions resolved (waiting on @piotrpalcz)



<!-- Sent from Reviewable.io -->

2023-10-26 13:39 UTC, merged