Add numeric representation of framework options
intel/ScaffoldingForGramine pull request #2
Opened 2023-08-23 13:07 UTC by oshogbo

In interactive mode, enable the selection of framework by either providing its name as a string or its sequence number.

2023-08-24 08:59 UTC, bsulich2 requested changes

2023-08-24 08:59 UTC, bsulich2 commented on graminescaffolding/utils.py
> +class GramineNumberObtions(GramineStorePrompt):
Typo in class name

2023-08-24 09:59 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/2)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bsulich2)

___
*[`graminescaffolding/utils.py` line 25 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/2#gh-1304023444:-Ncayt-J8Y3I61aTdXTA:bytum0d) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/1d5a9f3c7852f93bb08b81a0907c27a2ddd978d6/graminescaffolding/utils.py#L25)):*
<details><summary><i>Previously, bsulich2 wrote…</i></summary><blockquote>

Typo in class name
</blockquote></details>

Thx, fixed.


<!-- Sent from Reviewable.io -->

2023-08-24 10:08 UTC, bsulich2 approved these changes

2023-08-25 11:54 UTC, bsulich2 approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-09-06 18:18 UTC, merged